language: node_js

node_js:
  - '4.1'

env:
  - NODE_ENV="test" DB_USER="postgres" CXX=g++-4.8

addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - psql -c 'create database opendatacensus_test;' -U postgres

script: "npm run-script test-travis"

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
