language: node_js

node_js:
  - '4.1'

addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - psql -c 'create database opendatacensus_test;' -U postgres

env:
  - NODE_ENV="test" DB_USER="postgres" CXX=g++-4.8
